### ISSUE TITLE
Restore and maximize cosmetic issues

### ISSUE THREAD

**Issue by technoguy20000** [Bertware/bukkitgui2#20] opened 2015-01-02 17:40 UTC
In Windows 7, if you drag a window to the top of the screen, it should maximize, and once it's maximized, you should be able to drag the window down and it should restore. When you drag the BukkitGUI2 window to the top, it does not maximize, so it must be done manually, however, dragging the window in maximized mode does restore it, but the restore button in the top right corner does not change to a maximize button. It does update when you manually press the button. It's a purely cosmetic issue.

**Comment by Bertware** [comment] 2015-01-02 21:02
duplicate of #23

**Closed by Bertware** 2015-01-02 21:02 UTC
